namespace PatientIntake.DataAccess.Tests
{// <auto-generated />
 //
 // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
 //
 //    using PatientIntake.TestData;
 //
 //    var testUsers = TestUsers.FromJson(jsonString);

        using System;
        using System.Collections.Generic;

        using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class TestUsers
        {
            [JsonProperty("results")]
            public List<Result> Results { get; set; }

            [JsonProperty("info")]
            public Info Info { get; set; }
        }

        public partial class Info
        {
            [JsonProperty("seed")]
            public string Seed { get; set; }

            [JsonProperty("results")]
            public long Results { get; set; }

            [JsonProperty("page")]
            public long Page { get; set; }

            [JsonProperty("version")]
            public string Version { get; set; }
        }

        public partial class Result
        {
            [JsonProperty("gender")]
            public Gender Gender { get; set; }

            [JsonProperty("name")]
            public NameClass Name { get; set; }

            [JsonProperty("location")]
            public Location Location { get; set; }

            [JsonProperty("email")]
            public string Email { get; set; }

            [JsonProperty("login")]
            public Login Login { get; set; }

            [JsonProperty("dob")]
            public Dob Dob { get; set; }

            [JsonProperty("registered")]
            public Dob Registered { get; set; }

            [JsonProperty("phone")]
            public string Phone { get; set; }

            [JsonProperty("cell")]
            public string Cell { get; set; }

            [JsonProperty("id")]
            public Id Id { get; set; }

            [JsonProperty("picture")]
            public Picture Picture { get; set; }

            [JsonProperty("nat")]
            public Nat Nat { get; set; }
        }

        public partial class Dob
        {
            [JsonProperty("date")]
            public DateTimeOffset Date { get; set; }

            [JsonProperty("age")]
            public long Age { get; set; }
        }

        public partial class Id
        {
            [JsonProperty("name")]
            public NameEnum Name { get; set; }

            [JsonProperty("value")]
            public string Value { get; set; }
        }

        public partial class Location
        {
            [JsonProperty("street")]
            public Street Street { get; set; }

            [JsonProperty("city")]
            public string City { get; set; }

            [JsonProperty("state")]
            public string State { get; set; }

            [JsonProperty("country")]
            public Country Country { get; set; }

            [JsonProperty("postcode")]
            public Postcode Postcode { get; set; }

            [JsonProperty("coordinates")]
            public Coordinates Coordinates { get; set; }

            [JsonProperty("timezone")]
            public Timezone Timezone { get; set; }
        }

        public partial class Coordinates
        {
            [JsonProperty("latitude")]
            public string Latitude { get; set; }

            [JsonProperty("longitude")]
            public string Longitude { get; set; }
        }

        public partial class Street
        {
            [JsonProperty("number")]
            public long Number { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }
        }

        public partial class Timezone
        {
            [JsonProperty("offset")]
            public Offset Offset { get; set; }

            [JsonProperty("description")]
            public Description Description { get; set; }
        }

        public partial class Login
        {
            [JsonProperty("uuid")]
            public Guid Uuid { get; set; }

            [JsonProperty("username")]
            public string Username { get; set; }

            [JsonProperty("password")]
            public string Password { get; set; }

            [JsonProperty("salt")]
            public string Salt { get; set; }

            [JsonProperty("md5")]
            public string Md5 { get; set; }

            [JsonProperty("sha1")]
            public string Sha1 { get; set; }

            [JsonProperty("sha256")]
            public string Sha256 { get; set; }
        }

        public partial class NameClass
        {
            [JsonProperty("title")]
            public Title Title { get; set; }

            [JsonProperty("first")]
            public string First { get; set; }

            [JsonProperty("last")]
            public string Last { get; set; }
        }

        public partial class Picture
        {
            [JsonProperty("large")]
            public Uri Large { get; set; }

            [JsonProperty("medium")]
            public Uri Medium { get; set; }

            [JsonProperty("thumbnail")]
            public Uri Thumbnail { get; set; }
        }

        public enum Gender { Female, Male };

        public enum NameEnum { Avs, Bsn, Cpr, Dni, Empty, Fn, Hetu, Insee, Nino, Pps, Ssn, Tfn };

        public enum Country { Australia, Brazil, Canada, Denmark, Finland, France, Germany, Iran, Ireland, Netherlands, NewZealand, Norway, Spain, Switzerland, Turkey, UnitedKingdom, UnitedStates };

        public enum Description { AbuDhabiMuscatBakuTbilisi, AdelaideDarwin, Alaska, AlmatyDhakaColombo, AtlanticTimeCanadaCaracasLaPaz, AzoresCapeVerdeIslands, BaghdadRiyadhMoscowStPetersburg, BangkokHanoiJakarta, BeijingPerthSingaporeHongKong, BombayCalcuttaMadrasNewDelhi, BrazilBuenosAiresGeorgetown, BrusselsCopenhagenMadridParis, CentralTimeUsCanadaMexicoCity, EasternAustraliaGuamVladivostok, EasternTimeUsCanadaBogotaLima, EkaterinburgIslamabadKarachiTashkent, EniwetokKwajalein, Hawaii, Kabul, KaliningradSouthAfrica, Kathmandu, MagadanSolomonIslandsNewCaledonia, MidAtlantic, MidwayIslandSamoa, MountainTimeUsCanada, Newfoundland, PacificTimeUsCanada, Tehran, TokyoSeoulOsakaSapporoYakutsk, WesternEuropeTimeLondonLisbonCasablanca };

        public enum Offset { Offset100, Offset1000, Offset1100, Offset200, Offset300, Offset330, Offset400, Offset500, Offset600, Offset700, Offset800, Offset900, The000, The100, The1000, The1100, The1200, The200, The300, The330, The400, The430, The500, The530, The545, The600, The700, The800, The900, The930 };

        public enum Title { Madame, Mademoiselle, Miss, Monsieur, Mr, Mrs, Ms };

        public enum Nat { Au, Br, Ca, Ch, De, Dk, Es, Fi, Fr, Gb, Ie, Ir, Nl, No, Nz, Tr, Us };

        public partial struct Postcode
        {
            public long? Integer;
            public string String;

            public static implicit operator Postcode(long Integer) => new Postcode { Integer = Integer };
            public static implicit operator Postcode(string String) => new Postcode { String = String };
        }

        public partial class TestUsers
        {
            public static TestUsers FromJson(string json) => JsonConvert.DeserializeObject<TestUsers>(json, PatientIntake.DataAccess.Tests.Converter.Settings);
        }

        public static class Serialize
        {
            public static string ToJson(this TestUsers self) => JsonConvert.SerializeObject(self, PatientIntake.DataAccess.Tests.Converter.Settings);
        }

        internal static class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                DateParseHandling = DateParseHandling.None,
                Converters =
            {
                GenderConverter.Singleton,
                NameEnumConverter.Singleton,
                CountryConverter.Singleton,
                PostcodeConverter.Singleton,
                DescriptionConverter.Singleton,
                OffsetConverter.Singleton,
                TitleConverter.Singleton,
                NatConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            };
        }

        internal class GenderConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Gender) || t == typeof(Gender?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "female":
                        return Gender.Female;
                    case "male":
                        return Gender.Male;
                }
                throw new Exception("Cannot unmarshal type Gender");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Gender)untypedValue;
                switch (value)
                {
                    case Gender.Female:
                        serializer.Serialize(writer, "female");
                        return;
                    case Gender.Male:
                        serializer.Serialize(writer, "male");
                        return;
                }
                throw new Exception("Cannot marshal type Gender");
            }

            public static readonly GenderConverter Singleton = new GenderConverter();
        }

        internal class NameEnumConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(NameEnum) || t == typeof(NameEnum?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "":
                        return NameEnum.Empty;
                    case "AVS":
                        return NameEnum.Avs;
                    case "BSN":
                        return NameEnum.Bsn;
                    case "CPR":
                        return NameEnum.Cpr;
                    case "DNI":
                        return NameEnum.Dni;
                    case "FN":
                        return NameEnum.Fn;
                    case "HETU":
                        return NameEnum.Hetu;
                    case "INSEE":
                        return NameEnum.Insee;
                    case "NINO":
                        return NameEnum.Nino;
                    case "PPS":
                        return NameEnum.Pps;
                    case "SSN":
                        return NameEnum.Ssn;
                    case "TFN":
                        return NameEnum.Tfn;
                }
                throw new Exception("Cannot unmarshal type NameEnum");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (NameEnum)untypedValue;
                switch (value)
                {
                    case NameEnum.Empty:
                        serializer.Serialize(writer, "");
                        return;
                    case NameEnum.Avs:
                        serializer.Serialize(writer, "AVS");
                        return;
                    case NameEnum.Bsn:
                        serializer.Serialize(writer, "BSN");
                        return;
                    case NameEnum.Cpr:
                        serializer.Serialize(writer, "CPR");
                        return;
                    case NameEnum.Dni:
                        serializer.Serialize(writer, "DNI");
                        return;
                    case NameEnum.Fn:
                        serializer.Serialize(writer, "FN");
                        return;
                    case NameEnum.Hetu:
                        serializer.Serialize(writer, "HETU");
                        return;
                    case NameEnum.Insee:
                        serializer.Serialize(writer, "INSEE");
                        return;
                    case NameEnum.Nino:
                        serializer.Serialize(writer, "NINO");
                        return;
                    case NameEnum.Pps:
                        serializer.Serialize(writer, "PPS");
                        return;
                    case NameEnum.Ssn:
                        serializer.Serialize(writer, "SSN");
                        return;
                    case NameEnum.Tfn:
                        serializer.Serialize(writer, "TFN");
                        return;
                }
                throw new Exception("Cannot marshal type NameEnum");
            }

            public static readonly NameEnumConverter Singleton = new NameEnumConverter();
        }

        internal class CountryConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Country) || t == typeof(Country?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "Australia":
                        return Country.Australia;
                    case "Brazil":
                        return Country.Brazil;
                    case "Canada":
                        return Country.Canada;
                    case "Denmark":
                        return Country.Denmark;
                    case "Finland":
                        return Country.Finland;
                    case "France":
                        return Country.France;
                    case "Germany":
                        return Country.Germany;
                    case "Iran":
                        return Country.Iran;
                    case "Ireland":
                        return Country.Ireland;
                    case "Netherlands":
                        return Country.Netherlands;
                    case "New Zealand":
                        return Country.NewZealand;
                    case "Norway":
                        return Country.Norway;
                    case "Spain":
                        return Country.Spain;
                    case "Switzerland":
                        return Country.Switzerland;
                    case "Turkey":
                        return Country.Turkey;
                    case "United Kingdom":
                        return Country.UnitedKingdom;
                    case "United States":
                        return Country.UnitedStates;
                }
                throw new Exception("Cannot unmarshal type Country");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Country)untypedValue;
                switch (value)
                {
                    case Country.Australia:
                        serializer.Serialize(writer, "Australia");
                        return;
                    case Country.Brazil:
                        serializer.Serialize(writer, "Brazil");
                        return;
                    case Country.Canada:
                        serializer.Serialize(writer, "Canada");
                        return;
                    case Country.Denmark:
                        serializer.Serialize(writer, "Denmark");
                        return;
                    case Country.Finland:
                        serializer.Serialize(writer, "Finland");
                        return;
                    case Country.France:
                        serializer.Serialize(writer, "France");
                        return;
                    case Country.Germany:
                        serializer.Serialize(writer, "Germany");
                        return;
                    case Country.Iran:
                        serializer.Serialize(writer, "Iran");
                        return;
                    case Country.Ireland:
                        serializer.Serialize(writer, "Ireland");
                        return;
                    case Country.Netherlands:
                        serializer.Serialize(writer, "Netherlands");
                        return;
                    case Country.NewZealand:
                        serializer.Serialize(writer, "New Zealand");
                        return;
                    case Country.Norway:
                        serializer.Serialize(writer, "Norway");
                        return;
                    case Country.Spain:
                        serializer.Serialize(writer, "Spain");
                        return;
                    case Country.Switzerland:
                        serializer.Serialize(writer, "Switzerland");
                        return;
                    case Country.Turkey:
                        serializer.Serialize(writer, "Turkey");
                        return;
                    case Country.UnitedKingdom:
                        serializer.Serialize(writer, "United Kingdom");
                        return;
                    case Country.UnitedStates:
                        serializer.Serialize(writer, "United States");
                        return;
                }
                throw new Exception("Cannot marshal type Country");
            }

            public static readonly CountryConverter Singleton = new CountryConverter();
        }

        internal class PostcodeConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Postcode) || t == typeof(Postcode?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                switch (reader.TokenType)
                {
                    case JsonToken.Integer:
                        var integerValue = serializer.Deserialize<long>(reader);
                        return new Postcode { Integer = integerValue };
                    case JsonToken.String:
                    case JsonToken.Date:
                        var stringValue = serializer.Deserialize<string>(reader);
                        return new Postcode { String = stringValue };
                }
                throw new Exception("Cannot unmarshal type Postcode");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                var value = (Postcode)untypedValue;
                if (value.Integer != null)
                {
                    serializer.Serialize(writer, value.Integer.Value);
                    return;
                }
                if (value.String != null)
                {
                    serializer.Serialize(writer, value.String);
                    return;
                }
                throw new Exception("Cannot marshal type Postcode");
            }

            public static readonly PostcodeConverter Singleton = new PostcodeConverter();
        }

        internal class DescriptionConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Description) || t == typeof(Description?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "Abu Dhabi, Muscat, Baku, Tbilisi":
                        return Description.AbuDhabiMuscatBakuTbilisi;
                    case "Adelaide, Darwin":
                        return Description.AdelaideDarwin;
                    case "Alaska":
                        return Description.Alaska;
                    case "Almaty, Dhaka, Colombo":
                        return Description.AlmatyDhakaColombo;
                    case "Atlantic Time (Canada), Caracas, La Paz":
                        return Description.AtlanticTimeCanadaCaracasLaPaz;
                    case "Azores, Cape Verde Islands":
                        return Description.AzoresCapeVerdeIslands;
                    case "Baghdad, Riyadh, Moscow, St. Petersburg":
                        return Description.BaghdadRiyadhMoscowStPetersburg;
                    case "Bangkok, Hanoi, Jakarta":
                        return Description.BangkokHanoiJakarta;
                    case "Beijing, Perth, Singapore, Hong Kong":
                        return Description.BeijingPerthSingaporeHongKong;
                    case "Bombay, Calcutta, Madras, New Delhi":
                        return Description.BombayCalcuttaMadrasNewDelhi;
                    case "Brazil, Buenos Aires, Georgetown":
                        return Description.BrazilBuenosAiresGeorgetown;
                    case "Brussels, Copenhagen, Madrid, Paris":
                        return Description.BrusselsCopenhagenMadridParis;
                    case "Central Time (US & Canada), Mexico City":
                        return Description.CentralTimeUsCanadaMexicoCity;
                    case "Eastern Australia, Guam, Vladivostok":
                        return Description.EasternAustraliaGuamVladivostok;
                    case "Eastern Time (US & Canada), Bogota, Lima":
                        return Description.EasternTimeUsCanadaBogotaLima;
                    case "Ekaterinburg, Islamabad, Karachi, Tashkent":
                        return Description.EkaterinburgIslamabadKarachiTashkent;
                    case "Eniwetok, Kwajalein":
                        return Description.EniwetokKwajalein;
                    case "Hawaii":
                        return Description.Hawaii;
                    case "Kabul":
                        return Description.Kabul;
                    case "Kaliningrad, South Africa":
                        return Description.KaliningradSouthAfrica;
                    case "Kathmandu":
                        return Description.Kathmandu;
                    case "Magadan, Solomon Islands, New Caledonia":
                        return Description.MagadanSolomonIslandsNewCaledonia;
                    case "Mid-Atlantic":
                        return Description.MidAtlantic;
                    case "Midway Island, Samoa":
                        return Description.MidwayIslandSamoa;
                    case "Mountain Time (US & Canada)":
                        return Description.MountainTimeUsCanada;
                    case "Newfoundland":
                        return Description.Newfoundland;
                    case "Pacific Time (US & Canada)":
                        return Description.PacificTimeUsCanada;
                    case "Tehran":
                        return Description.Tehran;
                    case "Tokyo, Seoul, Osaka, Sapporo, Yakutsk":
                        return Description.TokyoSeoulOsakaSapporoYakutsk;
                    case "Western Europe Time, London, Lisbon, Casablanca":
                        return Description.WesternEuropeTimeLondonLisbonCasablanca;
                }
                throw new Exception("Cannot unmarshal type Description");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Description)untypedValue;
                switch (value)
                {
                    case Description.AbuDhabiMuscatBakuTbilisi:
                        serializer.Serialize(writer, "Abu Dhabi, Muscat, Baku, Tbilisi");
                        return;
                    case Description.AdelaideDarwin:
                        serializer.Serialize(writer, "Adelaide, Darwin");
                        return;
                    case Description.Alaska:
                        serializer.Serialize(writer, "Alaska");
                        return;
                    case Description.AlmatyDhakaColombo:
                        serializer.Serialize(writer, "Almaty, Dhaka, Colombo");
                        return;
                    case Description.AtlanticTimeCanadaCaracasLaPaz:
                        serializer.Serialize(writer, "Atlantic Time (Canada), Caracas, La Paz");
                        return;
                    case Description.AzoresCapeVerdeIslands:
                        serializer.Serialize(writer, "Azores, Cape Verde Islands");
                        return;
                    case Description.BaghdadRiyadhMoscowStPetersburg:
                        serializer.Serialize(writer, "Baghdad, Riyadh, Moscow, St. Petersburg");
                        return;
                    case Description.BangkokHanoiJakarta:
                        serializer.Serialize(writer, "Bangkok, Hanoi, Jakarta");
                        return;
                    case Description.BeijingPerthSingaporeHongKong:
                        serializer.Serialize(writer, "Beijing, Perth, Singapore, Hong Kong");
                        return;
                    case Description.BombayCalcuttaMadrasNewDelhi:
                        serializer.Serialize(writer, "Bombay, Calcutta, Madras, New Delhi");
                        return;
                    case Description.BrazilBuenosAiresGeorgetown:
                        serializer.Serialize(writer, "Brazil, Buenos Aires, Georgetown");
                        return;
                    case Description.BrusselsCopenhagenMadridParis:
                        serializer.Serialize(writer, "Brussels, Copenhagen, Madrid, Paris");
                        return;
                    case Description.CentralTimeUsCanadaMexicoCity:
                        serializer.Serialize(writer, "Central Time (US & Canada), Mexico City");
                        return;
                    case Description.EasternAustraliaGuamVladivostok:
                        serializer.Serialize(writer, "Eastern Australia, Guam, Vladivostok");
                        return;
                    case Description.EasternTimeUsCanadaBogotaLima:
                        serializer.Serialize(writer, "Eastern Time (US & Canada), Bogota, Lima");
                        return;
                    case Description.EkaterinburgIslamabadKarachiTashkent:
                        serializer.Serialize(writer, "Ekaterinburg, Islamabad, Karachi, Tashkent");
                        return;
                    case Description.EniwetokKwajalein:
                        serializer.Serialize(writer, "Eniwetok, Kwajalein");
                        return;
                    case Description.Hawaii:
                        serializer.Serialize(writer, "Hawaii");
                        return;
                    case Description.Kabul:
                        serializer.Serialize(writer, "Kabul");
                        return;
                    case Description.KaliningradSouthAfrica:
                        serializer.Serialize(writer, "Kaliningrad, South Africa");
                        return;
                    case Description.Kathmandu:
                        serializer.Serialize(writer, "Kathmandu");
                        return;
                    case Description.MagadanSolomonIslandsNewCaledonia:
                        serializer.Serialize(writer, "Magadan, Solomon Islands, New Caledonia");
                        return;
                    case Description.MidAtlantic:
                        serializer.Serialize(writer, "Mid-Atlantic");
                        return;
                    case Description.MidwayIslandSamoa:
                        serializer.Serialize(writer, "Midway Island, Samoa");
                        return;
                    case Description.MountainTimeUsCanada:
                        serializer.Serialize(writer, "Mountain Time (US & Canada)");
                        return;
                    case Description.Newfoundland:
                        serializer.Serialize(writer, "Newfoundland");
                        return;
                    case Description.PacificTimeUsCanada:
                        serializer.Serialize(writer, "Pacific Time (US & Canada)");
                        return;
                    case Description.Tehran:
                        serializer.Serialize(writer, "Tehran");
                        return;
                    case Description.TokyoSeoulOsakaSapporoYakutsk:
                        serializer.Serialize(writer, "Tokyo, Seoul, Osaka, Sapporo, Yakutsk");
                        return;
                    case Description.WesternEuropeTimeLondonLisbonCasablanca:
                        serializer.Serialize(writer, "Western Europe Time, London, Lisbon, Casablanca");
                        return;
                }
                throw new Exception("Cannot marshal type Description");
            }

            public static readonly DescriptionConverter Singleton = new DescriptionConverter();
        }

        internal class OffsetConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Offset) || t == typeof(Offset?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "+10:00":
                        return Offset.Offset1000;
                    case "+11:00":
                        return Offset.Offset1100;
                    case "+1:00":
                        return Offset.Offset100;
                    case "+2:00":
                        return Offset.The200;
                    case "+3:00":
                        return Offset.Offset300;
                    case "+3:30":
                        return Offset.The330;
                    case "+4:00":
                        return Offset.Offset400;
                    case "+4:30":
                        return Offset.The430;
                    case "+5:00":
                        return Offset.The500;
                    case "+5:30":
                        return Offset.The530;
                    case "+5:45":
                        return Offset.The545;
                    case "+6:00":
                        return Offset.Offset600;
                    case "+7:00":
                        return Offset.Offset700;
                    case "+8:00":
                        return Offset.The800;
                    case "+9:00":
                        return Offset.The900;
                    case "+9:30":
                        return Offset.The930;
                    case "-10:00":
                        return Offset.The1000;
                    case "-11:00":
                        return Offset.The1100;
                    case "-12:00":
                        return Offset.The1200;
                    case "-1:00":
                        return Offset.The100;
                    case "-2:00":
                        return Offset.Offset200;
                    case "-3:00":
                        return Offset.The300;
                    case "-3:30":
                        return Offset.Offset330;
                    case "-4:00":
                        return Offset.The400;
                    case "-5:00":
                        return Offset.Offset500;
                    case "-6:00":
                        return Offset.The600;
                    case "-7:00":
                        return Offset.The700;
                    case "-8:00":
                        return Offset.Offset800;
                    case "-9:00":
                        return Offset.Offset900;
                    case "0:00":
                        return Offset.The000;
                }
                throw new Exception("Cannot unmarshal type Offset");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Offset)untypedValue;
                switch (value)
                {
                    case Offset.Offset1000:
                        serializer.Serialize(writer, "+10:00");
                        return;
                    case Offset.Offset1100:
                        serializer.Serialize(writer, "+11:00");
                        return;
                    case Offset.Offset100:
                        serializer.Serialize(writer, "+1:00");
                        return;
                    case Offset.The200:
                        serializer.Serialize(writer, "+2:00");
                        return;
                    case Offset.Offset300:
                        serializer.Serialize(writer, "+3:00");
                        return;
                    case Offset.The330:
                        serializer.Serialize(writer, "+3:30");
                        return;
                    case Offset.Offset400:
                        serializer.Serialize(writer, "+4:00");
                        return;
                    case Offset.The430:
                        serializer.Serialize(writer, "+4:30");
                        return;
                    case Offset.The500:
                        serializer.Serialize(writer, "+5:00");
                        return;
                    case Offset.The530:
                        serializer.Serialize(writer, "+5:30");
                        return;
                    case Offset.The545:
                        serializer.Serialize(writer, "+5:45");
                        return;
                    case Offset.Offset600:
                        serializer.Serialize(writer, "+6:00");
                        return;
                    case Offset.Offset700:
                        serializer.Serialize(writer, "+7:00");
                        return;
                    case Offset.The800:
                        serializer.Serialize(writer, "+8:00");
                        return;
                    case Offset.The900:
                        serializer.Serialize(writer, "+9:00");
                        return;
                    case Offset.The930:
                        serializer.Serialize(writer, "+9:30");
                        return;
                    case Offset.The1000:
                        serializer.Serialize(writer, "-10:00");
                        return;
                    case Offset.The1100:
                        serializer.Serialize(writer, "-11:00");
                        return;
                    case Offset.The1200:
                        serializer.Serialize(writer, "-12:00");
                        return;
                    case Offset.The100:
                        serializer.Serialize(writer, "-1:00");
                        return;
                    case Offset.Offset200:
                        serializer.Serialize(writer, "-2:00");
                        return;
                    case Offset.The300:
                        serializer.Serialize(writer, "-3:00");
                        return;
                    case Offset.Offset330:
                        serializer.Serialize(writer, "-3:30");
                        return;
                    case Offset.The400:
                        serializer.Serialize(writer, "-4:00");
                        return;
                    case Offset.Offset500:
                        serializer.Serialize(writer, "-5:00");
                        return;
                    case Offset.The600:
                        serializer.Serialize(writer, "-6:00");
                        return;
                    case Offset.The700:
                        serializer.Serialize(writer, "-7:00");
                        return;
                    case Offset.Offset800:
                        serializer.Serialize(writer, "-8:00");
                        return;
                    case Offset.Offset900:
                        serializer.Serialize(writer, "-9:00");
                        return;
                    case Offset.The000:
                        serializer.Serialize(writer, "0:00");
                        return;
                }
                throw new Exception("Cannot marshal type Offset");
            }

            public static readonly OffsetConverter Singleton = new OffsetConverter();
        }

        internal class TitleConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Title) || t == typeof(Title?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "Madame":
                        return Title.Madame;
                    case "Mademoiselle":
                        return Title.Mademoiselle;
                    case "Miss":
                        return Title.Miss;
                    case "Monsieur":
                        return Title.Monsieur;
                    case "Mr":
                        return Title.Mr;
                    case "Mrs":
                        return Title.Mrs;
                    case "Ms":
                        return Title.Ms;
                }
                throw new Exception("Cannot unmarshal type Title");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Title)untypedValue;
                switch (value)
                {
                    case Title.Madame:
                        serializer.Serialize(writer, "Madame");
                        return;
                    case Title.Mademoiselle:
                        serializer.Serialize(writer, "Mademoiselle");
                        return;
                    case Title.Miss:
                        serializer.Serialize(writer, "Miss");
                        return;
                    case Title.Monsieur:
                        serializer.Serialize(writer, "Monsieur");
                        return;
                    case Title.Mr:
                        serializer.Serialize(writer, "Mr");
                        return;
                    case Title.Mrs:
                        serializer.Serialize(writer, "Mrs");
                        return;
                    case Title.Ms:
                        serializer.Serialize(writer, "Ms");
                        return;
                }
                throw new Exception("Cannot marshal type Title");
            }

            public static readonly TitleConverter Singleton = new TitleConverter();
        }

        internal class NatConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(Nat) || t == typeof(Nat?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                switch (value)
                {
                    case "AU":
                        return Nat.Au;
                    case "BR":
                        return Nat.Br;
                    case "CA":
                        return Nat.Ca;
                    case "CH":
                        return Nat.Ch;
                    case "DE":
                        return Nat.De;
                    case "DK":
                        return Nat.Dk;
                    case "ES":
                        return Nat.Es;
                    case "FI":
                        return Nat.Fi;
                    case "FR":
                        return Nat.Fr;
                    case "GB":
                        return Nat.Gb;
                    case "IE":
                        return Nat.Ie;
                    case "IR":
                        return Nat.Ir;
                    case "NL":
                        return Nat.Nl;
                    case "NO":
                        return Nat.No;
                    case "NZ":
                        return Nat.Nz;
                    case "TR":
                        return Nat.Tr;
                    case "US":
                        return Nat.Us;
                }
                throw new Exception("Cannot unmarshal type Nat");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (Nat)untypedValue;
                switch (value)
                {
                    case Nat.Au:
                        serializer.Serialize(writer, "AU");
                        return;
                    case Nat.Br:
                        serializer.Serialize(writer, "BR");
                        return;
                    case Nat.Ca:
                        serializer.Serialize(writer, "CA");
                        return;
                    case Nat.Ch:
                        serializer.Serialize(writer, "CH");
                        return;
                    case Nat.De:
                        serializer.Serialize(writer, "DE");
                        return;
                    case Nat.Dk:
                        serializer.Serialize(writer, "DK");
                        return;
                    case Nat.Es:
                        serializer.Serialize(writer, "ES");
                        return;
                    case Nat.Fi:
                        serializer.Serialize(writer, "FI");
                        return;
                    case Nat.Fr:
                        serializer.Serialize(writer, "FR");
                        return;
                    case Nat.Gb:
                        serializer.Serialize(writer, "GB");
                        return;
                    case Nat.Ie:
                        serializer.Serialize(writer, "IE");
                        return;
                    case Nat.Ir:
                        serializer.Serialize(writer, "IR");
                        return;
                    case Nat.Nl:
                        serializer.Serialize(writer, "NL");
                        return;
                    case Nat.No:
                        serializer.Serialize(writer, "NO");
                        return;
                    case Nat.Nz:
                        serializer.Serialize(writer, "NZ");
                        return;
                    case Nat.Tr:
                        serializer.Serialize(writer, "TR");
                        return;
                    case Nat.Us:
                        serializer.Serialize(writer, "US");
                        return;
                }
                throw new Exception("Cannot marshal type Nat");
            }

            public static readonly NatConverter Singleton = new NatConverter();
        }
    }




