<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PatientIntake.Model\PatientIntake.Model.csproj" />
    <ProjectReference Include="..\PatientIntake.Utilities\PatientIntake.Utilities.csproj" />
  </ItemGroup>

</Project>
